arch = [
    "yazi",
    "bat",
    "fastfetch",
    "man-db",
    "man-pages",
    "jq",
    "unzip",
    "ripgrep",
    "fzy",
    "playerctl",
    "reflector",
    "libqalculate",
    "yt-dlp",
    "7zip",
    "trash-cli",
    "fd",
    "zoxide",
    "btop",
    "eza",
]
